// Generated by train_approx88_cascade.py
// MRED=0.0303667713 MED=263.8350219727 ER=0.8349914551 WCE=4034

module approx88_cascade(input wire [7:0] a, input wire [7:0] b, output wire [15:0] prod);
wire [1:0] ah=a[7:6], bh=b[7:6]; wire [5:0] al=a[5:0], bl=b[5:0];
wire [11:0] ll; wire [7:0] hl, lh; wire hh_0, hh_1, hh_2; wire [4:0] hh;
approx66_cross_low U_LL(.a(al),.b(bl),.prod(ll));
approx62_hl U_HL(.a(bl),.b(ah),.prod(hl));
approx62_lh U_LH(.a(al),.b(bh),.prod(lh));
LUT6 #(.INIT(64'h8000000000000000)) LUT_HH0(.I0(a[6]),.I1(b[6]),.I2(1'b1),.I3(1'b1),.I4(1'b1),.I5(1'b1),.O(hh_0));
LUT6_2 #(.INIT(64'h8000800078887888)) LUT_HH12(.I0(a[7]),.I1(b[6]),.I2(a[6]),.I3(b[7]),.I4(1'b1),.I5(1'b1),.O6(hh_2),.O5(hh_1));
assign hh={a[7],b[7],hh_2,hh_1,hh_0};
comp88_cascade U_COMP(.hh(hh),.hl(hl),.lh(lh),.ll(ll),.prod(prod));
endmodule

module approx66_cross_low(input wire [5:0] a,input wire [5:0] b,output wire [11:0] prod);
wire [7:0] plow,pmid,phigh;
approx62_low U_LOW(.a(a),.b(b[1:0]),.prod(plow));
approx62_mid U_MID(.a(a),.b(b[3:2]),.prod(pmid));
approx62_high U_HIGH(.a(a),.b(b[5:4]),.prod(phigh));
comp66_pair_cross U_COMP(.plow(plow),.pmid(pmid),.phigh(phigh),.prod(prod));
endmodule

module approx62_low(input wire [5:0] a,input wire [1:0] b,output wire [7:0] prod);
LUT6_2 #(.INIT(64'hEAC02578A0A0D5DD)) LUT6_inst1(.I0(b[0]),.I1(b[1]),.I2(a[0]),.I3(a[1]),.I4(1'b1),.I5(1'b1),.O5(prod[0]),.O6(prod[1]));
LUT6_2 #(.INIT(64'hEEAACC00EAC0EAC0)) LUT6_inst2(.I0(b[0]),.I1(b[1]),.I2(a[1]),.I3(a[2]),.I4(a[3]),.I5(1'b1),.O5(prod[2]),.O6(prod[3]));
LUT6_2 #(.INIT(64'hD4BA5400C8C062C0)) LUT6_inst3(.I0(b[0]),.I1(b[1]),.I2(a[3]),.I3(a[4]),.I4(a[5]),.I5(1'b1),.O5(prod[4]),.O6(prod[5]));
LUT6_2 #(.INIT(64'h93001791738063CF)) LUT6_inst4(.I0(b[0]),.I1(b[1]),.I2(a[4]),.I3(a[5]),.I4(1'b1),.I5(1'b1),.O5(prod[6]),.O6(prod[7]));
endmodule

module approx62_mid(input wire [5:0] a,input wire [1:0] b,output wire [7:0] prod);
LUT6_2 #(.INIT(64'hEAC02578A0A0D5DD)) LUT6_inst1(.I0(b[0]),.I1(b[1]),.I2(a[0]),.I3(a[1]),.I4(1'b1),.I5(1'b1),.O5(prod[0]),.O6(prod[1]));
LUT6_2 #(.INIT(64'hEE22CC00C840EAC0)) LUT6_inst2(.I0(b[0]),.I1(b[1]),.I2(a[1]),.I3(a[2]),.I4(a[3]),.I5(1'b1),.O5(prod[2]),.O6(prod[3]));
LUT6_2 #(.INIT(64'hC4C82C80CC9D8A40)) LUT6_inst3(.I0(b[0]),.I1(b[1]),.I2(a[3]),.I3(a[4]),.I4(a[5]),.I5(1'b1),.O5(prod[4]),.O6(prod[5]));
LUT6_2 #(.INIT(64'h91201791EEC063CF)) LUT6_inst4(.I0(b[0]),.I1(b[1]),.I2(a[4]),.I3(a[5]),.I4(1'b1),.I5(1'b1),.O5(prod[6]),.O6(prod[7]));
endmodule

module approx62_high(input wire [5:0] a,input wire [1:0] b,output wire [7:0] prod);
LUT6_2 #(.INIT(64'hEAC02578A0A0D5DD)) LUT6_inst1(.I0(b[0]),.I1(b[1]),.I2(a[0]),.I3(a[1]),.I4(1'b1),.I5(1'b1),.O5(prod[0]),.O6(prod[1]));
LUT6_2 #(.INIT(64'hEE62CC00E608EAC0)) LUT6_inst2(.I0(b[0]),.I1(b[1]),.I2(a[1]),.I3(a[2]),.I4(a[3]),.I5(1'b1),.O5(prod[2]),.O6(prod[3]));
LUT6_2 #(.INIT(64'h44C8E6C0759D54BF)) LUT6_inst3(.I0(b[0]),.I1(b[1]),.I2(a[3]),.I3(a[4]),.I4(a[5]),.I5(1'b1),.O5(prod[4]),.O6(prod[5]));
LUT6_2 #(.INIT(64'h80001791EE8063CF)) LUT6_inst4(.I0(b[0]),.I1(b[1]),.I2(a[4]),.I3(a[5]),.I4(1'b1),.I5(1'b1),.O5(prod[6]),.O6(prod[7]));
endmodule

module approx62_hl(input wire [5:0] a,input wire [1:0] b,output wire [7:0] prod);
LUT6_2 #(.INIT(64'hEAC00000A8A00000)) LUT6_inst1(.I0(b[0]),.I1(b[1]),.I2(a[0]),.I3(a[1]),.I4(1'b1),.I5(1'b1),.O5(prod[0]),.O6(prod[1]));
LUT6_2 #(.INIT(64'hEEAACC00EAC0EAC0)) LUT6_inst2(.I0(b[0]),.I1(b[1]),.I2(a[1]),.I3(a[2]),.I4(a[3]),.I5(1'b1),.O5(prod[2]),.O6(prod[3]));
LUT6_2 #(.INIT(64'hE6AACC006AC0EAC0)) LUT6_inst3(.I0(b[0]),.I1(b[1]),.I2(a[3]),.I3(a[4]),.I4(a[5]),.I5(1'b1),.O5(prod[4]),.O6(prod[5]));
LUT6_2 #(.INIT(64'h800000004C000000)) LUT6_inst4(.I0(b[0]),.I1(b[1]),.I2(a[4]),.I3(a[5]),.I4(1'b1),.I5(1'b1),.O5(prod[6]),.O6(prod[7]));
endmodule

module approx62_lh(input wire [5:0] a,input wire [1:0] b,output wire [7:0] prod);
LUT6_2 #(.INIT(64'hEAC00000A8A00000)) LUT6_inst1(.I0(b[0]),.I1(b[1]),.I2(a[0]),.I3(a[1]),.I4(1'b1),.I5(1'b1),.O5(prod[0]),.O6(prod[1]));
LUT6_2 #(.INIT(64'hEEAACC00EAC0EAC0)) LUT6_inst2(.I0(b[0]),.I1(b[1]),.I2(a[1]),.I3(a[2]),.I4(a[3]),.I5(1'b1),.O5(prod[2]),.O6(prod[3]));
LUT6_2 #(.INIT(64'hE6AACC006AC0EAC0)) LUT6_inst3(.I0(b[0]),.I1(b[1]),.I2(a[3]),.I3(a[4]),.I4(a[5]),.I5(1'b1),.O5(prod[4]),.O6(prod[5]));
LUT6_2 #(.INIT(64'h800000004C000000)) LUT6_inst4(.I0(b[0]),.I1(b[1]),.I2(a[4]),.I3(a[5]),.I4(1'b1),.I5(1'b1),.O5(prod[6]),.O6(prod[7]));
endmodule

module comp66_pair_cross(input wire [7:0] plow,input wire [7:0] pmid,input wire [7:0] phigh,output wire [11:0] prod);
assign prod[0]=plow[0]; assign prod[1]=plow[1]; assign prod[10]=phigh[6]; assign prod[11]=phigh[7];
LUT6_2 #(.INIT(64'h112BFFF8EB5EFEE6)) u_comp23(.I0(plow[2]),.I1(pmid[0]),.I2(plow[3]),.I3(pmid[1]),.I4(1'b0),.I5(1'b1),.O5(prod[2]),.O6(prod[3]));
LUT6 #(.INIT(64'hEFFFAEF6CCFECE96)) u_comp4(.I0(plow[4]),.I1(pmid[2]),.I2(phigh[0]),.I3(plow[5]),.I4(pmid[3]),.I5(phigh[1]),.O(prod[4]));
LUT6 #(.INIT(64'hFFFFABF7EEFFEFE8)) u_comp5(.I0(plow[4]),.I1(pmid[2]),.I2(phigh[0]),.I3(plow[5]),.I4(pmid[3]),.I5(phigh[1]),.O(prod[5]));
LUT6 #(.INIT(64'hFDF754FCF64C4496)) u_comp6(.I0(plow[6]),.I1(pmid[4]),.I2(phigh[2]),.I3(plow[7]),.I4(pmid[5]),.I5(phigh[3]),.O(prod[6]));
LUT6 #(.INIT(64'hCDFF84FFFD8F4588)) u_comp7(.I0(plow[6]),.I1(pmid[4]),.I2(phigh[2]),.I3(plow[7]),.I4(pmid[5]),.I5(phigh[3]),.O(prod[7]));
LUT6_2 #(.INIT(64'h8C5CEE804897D928)) u_comp89(.I0(pmid[6]),.I1(phigh[4]),.I2(pmid[7]),.I3(phigh[5]),.I4(1'b0),.I5(1'b1),.O5(prod[8]),.O6(prod[9]));
endmodule

module comp88_cascade(input wire [4:0] hh,input wire [7:0] hl,input wire [7:0] lh,input wire [11:0] ll,output wire [15:0] prod);
wire [8:0] a_reg; wire [7:0] b_reg,c_reg; wire [11:0] p,g; wire [12:0] c_i; wire [11:0] sum;
assign a_reg[5:0]=ll[11:6]; assign a_reg[8:6]=hh[2:0]; assign b_reg=lh; assign c_reg=hl;
assign prod[5:0]=ll[5:0]; assign g[11:9]=3'b000; assign p[11:9]={2'b00,g[8]}; assign c_i[0]=1'b0;
LUT6_2 #(.INIT(64'h96969696E8E8E8E8)) u88_gp0(.I0(c_reg[0]),.I1(b_reg[0]),.I2(a_reg[0]),.I3(1'b1),.I4(1'b1),.I5(1'b1),.O6(p[0]),.O5(g[0]));
LUT6_2 #(.INIT(64'h09966996E8E8E8E8)) u88_gp1(.I0(c_reg[1]),.I1(b_reg[1]),.I2(a_reg[1]),.I3(g[0]),.I4(1'b1),.I5(1'b1),.O6(p[1]),.O5(g[1]));
LUT6_2 #(.INIT(64'h69966996E8E8E8E8)) u88_gp2(.I0(c_reg[2]),.I1(b_reg[2]),.I2(a_reg[2]),.I3(g[1]),.I4(1'b1),.I5(1'b1),.O6(p[2]),.O5(g[2]));
LUT6_2 #(.INIT(64'h29966996E8E8E8E8)) u88_gp3(.I0(c_reg[3]),.I1(b_reg[3]),.I2(a_reg[3]),.I3(g[2]),.I4(1'b1),.I5(1'b1),.O6(p[3]),.O5(g[3]));
LUT6_2 #(.INIT(64'h69966996E8E8E8E8)) u88_gp4(.I0(c_reg[4]),.I1(b_reg[4]),.I2(a_reg[4]),.I3(g[3]),.I4(1'b1),.I5(1'b1),.O6(p[4]),.O5(g[4]));
LUT6_2 #(.INIT(64'h69966996E8E8E8E8)) u88_gp5(.I0(c_reg[5]),.I1(b_reg[5]),.I2(a_reg[5]),.I3(g[4]),.I4(1'b1),.I5(1'b1),.O6(p[5]),.O5(g[5]));
LUT6_2 #(.INIT(64'h69966996E8E8E8E8)) u88_gp6(.I0(c_reg[6]),.I1(b_reg[6]),.I2(a_reg[6]),.I3(g[5]),.I4(1'b1),.I5(1'b1),.O6(p[6]),.O5(g[6]));
LUT6_2 #(.INIT(64'h69966996E8E8E8E8)) u88_gp7(.I0(c_reg[7]),.I1(b_reg[7]),.I2(a_reg[7]),.I3(g[6]),.I4(1'b1),.I5(1'b1),.O6(p[7]),.O5(g[7]));
LUT6_2 #(.INIT(64'h96669666A000A000)) u88_gp8(.I0(a_reg[8]),.I1(g[7]),.I2(hh[4]),.I3(hh[3]),.I4(1'b1),.I5(1'b1),.O6(p[8]),.O5(g[8]));
CARRY4 CARRY4_0(.CO(c_i[4:1]),.O(sum[3:0]),.CI(c_i[0]),.CYINIT(1'b0),.DI({g[2:0],1'b0}),.S(p[3:0]));
CARRY4 CARRY4_1(.CO(c_i[8:5]),.O(sum[7:4]),.CI(c_i[4]),.CYINIT(1'b0),.DI(g[6:3]),.S(p[7:4]));
CARRY4 CARRY4_2(.CO(c_i[12:9]),.O(sum[11:8]),.CI(c_i[8]),.CYINIT(1'b0),.DI(g[10:7]),.S(p[11:8]));
assign prod[15:6]=sum[9:0];
endmodule
