// Final compressor for the signed 8x8 multiplier.
//
// The two biased 6x2 cross products are aligned at product bit 6.  This block
// simultaneously performs the final three-row compression, removes their
// combined bias, and applies the Baugh-Wooley sign correction.
//
// The a6&b6 high-product bit is deliberately NOT generated by a separate LUT.
// It is folded into bit6_lut from the raw a6 and b6 inputs.
// Resources: 9 LUT6_2 + 3 CARRY4.
module s88m_comp (
    input  wire [1:0]  a_hi,
    input  wire [1:0]  b_hi,
    input  wire        high_xor,
    input  wire [7:0]  hl_bias,
    input  wire [7:0]  lh_bias,
    input  wire [11:0] ll,
    output wire [15:0] prod
);

wire [7:0] b_row;
wire [7:0] c_row;
wire [11:0] p;
wire [11:0] g;

assign b_row     = lh_bias;
assign c_row     = hl_bias;
assign prod[5:0] = ll[5:0];

assign g[11:9] = 3'b000;
assign p[11:9] = {2'b00, g[8]};

// Relative column 0 (absolute product column 6).
LUT6_2 #(
    .INIT(64'h96969696e8e8e8e8)
) csa0_lut (
    .I0(c_row[0]), .I1(b_row[0]), .I2(ll[6]),
    .I3(1'b1), .I4(1'b1), .I5(1'b1),
    .O6(p[0]), .O5(g[0])
);

// Relative columns 1..5 use the upper six bits of the unsigned 6x6 product.
genvar i;
generate
    for (i = 1; i < 6; i = i + 1) begin : csa_gp_1_to_5
        LUT6_2 #(
            .INIT(64'h69966996e8e8e8e8)
        ) csa_lut (
            .I0(c_row[i]), .I1(b_row[i]), .I2(ll[i+6]), .I3(g[i-1]),
            .I4(1'b1), .I5(1'b1),
            .O6(p[i]), .O5(g[i])
        );
    end
endgenerate

// Relative column 6 (absolute product column 12).
// z = a_hi[0] & b_hi[0]
// O5: g6 = majority(c6, b6, z)
// O6: p6 = c6 ^ b6 ^ z ^ g5
// Computing z inside this LUT saves one complete top-level LUT6_2.
LUT6_2 #(
    .INIT(64'h69999666e888e888)
) bit6_lut (
    .I0(c_row[6]), .I1(b_row[6]),
    .I2(a_hi[0]), .I3(b_hi[0]), .I4(g[5]), .I5(1'b1),
    .O6(p[6]), .O5(g[6])
);

// Relative column 7 contains the encoded -2 cross terms of the signed 2x2
// high product.
LUT6_2 #(
    .INIT(64'h69966996e8e8e8e8)
) bit7_lut (
    .I0(c_row[7]), .I1(b_row[7]), .I2(high_xor), .I3(g[6]),
    .I4(1'b1), .I5(1'b1),
    .O6(p[7]), .O5(g[7])
);

// Recompute high_bw directly here instead of spending a top-level LUT output:
//   high_bw = ~(a7 & b6) & ~(a6 & b7)
// O6: p8 = high_bw ^ (a7 & b7) ^ g7
// O5: g8 = ~(high_bw & (a7 & b7))
// All five independent inputs fit exactly in one LUT6_2. Complementing g8
// folds the final 16'h8000 Baugh-Wooley correction and both cross-product
// biases into the existing final carry chain.
LUT6_2 #(
    .INIT(64'h5288ad77fdfffdff)
) signed_top_lut (
    .I0(a_hi[1]), .I1(b_hi[0]), .I2(a_hi[0]),
    .I3(b_hi[1]), .I4(g[7]), .I5(1'b1),
    .O6(p[8]), .O5(g[8])
);

wire [12:0] carry;
wire [11:0] sum;
assign carry[0] = 1'b0;

CARRY4 carry_0 (
    .CO(carry[4:1]), .O(sum[3:0]),
    .CI(carry[0]), .CYINIT(1'b0),
    .DI({g[2:0], 1'b0}), .S(p[3:0])
);

CARRY4 carry_1 (
    .CO(carry[8:5]), .O(sum[7:4]),
    .CI(carry[4]), .CYINIT(1'b0),
    .DI(g[6:3]), .S(p[7:4])
);

CARRY4 carry_2 (
    .CO(carry[12:9]), .O(sum[11:8]),
    .CI(carry[8]), .CYINIT(1'b0),
    .DI(g[10:7]), .S(p[11:8])
);

assign prod[15:6] = sum[9:0];

endmodule
