// Exact two's-complement signed 8x8 multiplier for Xilinx 6-input LUT FPGA.
//
// Combinational datapath primitives only:
//   31 LUT6_2 + 16 LUT6 = 47 physical LUTs
//    7 CARRY4
//
// No DSP, inferred multiplier, inferred adder, register, or RAM is used.
module signed88_min (
    input  wire signed [7:0]  a,
    input  wire signed [7:0]  b,
    output wire signed [15:0] prod
);

wire [5:0]  al;
wire [5:0]  bl;
wire [11:0] ll;
wire [7:0]  hl_bias;
wire [7:0]  lh_bias;
wire        hl_high_n;
wire        lh_high_n;
wire        high_xor;

assign al = a[5:0];
assign bl = b[5:0];

// O5 supplies the second signed 6x2 child's final complemented sign-row bit.
// O6 simultaneously encodes the -2 cross terms of the signed high 2x2 block.
// The first 6x2 high_n is generated by an otherwise unused O5 in s88m_comp66.
LUT6_2 #(
    .INIT(64'h3cccf00077777777)
) shared_sign_lut (
    .I0(a[5]), .I1(b[7]), .I2(a[7]),
    .I3(b[6]), .I4(a[6]), .I5(1'b1),
    .O6(high_xor), .O5(lh_high_n)
);

// Low 6x6 is unsigned and follows the carry-light 8x8_50 decomposition.
s88m_mul66 low_multiplier (
    .a(al), .b(bl), .shared_sign(a[7]),
    .prod(ll), .shared_high_n(hl_high_n)
);

// a = al + 64*signed(a[7:6]), b = bl + 64*signed(b[7:6]).
// Each cross term is returned with a +128 bias.
s88m_bw62 high_a_cross (
    .x(bl), .y(a[7:6]),
    .high_n(hl_high_n), .biased_prod(hl_bias)
);

s88m_bw62 high_b_cross (
    .x(al), .y(b[7:6]),
    .high_n(lh_high_n), .biased_prod(lh_bias)
);

s88m_comp final_compressor (
    .a_hi(a[7:6]), .b_hi(b[7:6]),
    .high_xor(high_xor),
    .hl_bias(hl_bias), .lh_bias(lh_bias), .ll(ll),
    .prod(prod)
);

endmodule
